"""
Epistemic Kernel — First-Class Epistemic Distinction.

Every internal representation in NurosOS carries an epistemic label that
identifies how the representation came to exist. This is a core safety
and scientific-integrity feature.

Epistemic Labels:
    OBSERVED   — Direct sensor data or verified external input
    INFERRED   — Interpretation or deduction from observations
    REMEMBERED — Retrieved from memory (may be outdated or revised)
    IMAGINED   — Internally generated possibility (not grounded in reality)
    PREDICTED  — Expected future state (carries uncertainty)
    SIMULATED  — Result generated by an internal model
    ACTED      — Externally executed operation (has real-world consequences)

Critical Invariants:
    - A SIMULATED result must NEVER silently become an OBSERVATION.
    - An IMAGINED state must NEVER silently become a REMEMBERED fact.
    - Epistemic downgrade (e.g., OBSERVED → INFERRED after processing)
      requires explicit annotation.
    - Epistemic upgrade (e.g., PREDICTED → OBSERVED after verification)
      requires explicit evidence and audit trail.

Implementation Status: IMPLEMENTED
"""

from __future__ import annotations

import time
import uuid
from dataclasses import dataclass, field
from enum import Enum, IntEnum
from typing import Any, Optional


class EpistemicLabel(IntEnum):
    """
    First-class epistemic labels for internal representations.

    The ordering reflects a rough "grounding strength" hierarchy:
    OBSERVED is most grounded in reality; IMAGINED is least grounded.
    This ordering is NOT a total ordering on truth or reliability —
    an inferred conclusion may be more reliable than a noisy observation.
    The hierarchy is about *source type*, not *correctness*.
    """
    OBSERVED = 1     # Direct sensor data, verified external input
    INFERRED = 2     # Interpretation or deduction from observations
    REMEMBERED = 3   # Retrieved from memory (may be outdated/revisioned)
    PREDICTED = 4    # Expected future state (carries uncertainty)
    SIMULATED = 5    # Result generated by an internal model
    IMAGINED = 6     # Internally generated possibility (not grounded)
    ACTED = 7        # Externally executed operation (real-world consequences)

    @property
    def is_grounded(self) -> bool:
        """Whether this label represents information grounded in direct experience."""
        return self in (EpistemicLabel.OBSERVED, EpistemicLabel.ACTED)

    @property
    def is_speculative(self) -> bool:
        """Whether this label represents internally generated, ungrounded information."""
        return self in (EpistemicLabel.IMAGINED, EpistemicLabel.SIMULATED, EpistemicLabel.PREDICTED)

    @property
    def description(self) -> str:
        """Human-readable description of this epistemic label."""
        descriptions = {
            EpistemicLabel.OBSERVED: "Direct sensor data or verified external input",
            EpistemicLabel.INFERRED: "Interpretation or deduction from observations",
            EpistemicLabel.REMEMBERED: "Retrieved from memory (may be outdated or revised)",
            EpistemicLabel.PREDICTED: "Expected future state (carries uncertainty)",
            EpistemicLabel.SIMULATED: "Result generated by an internal model",
            EpistemicLabel.IMAGINED: "Internally generated possibility (not grounded in reality)",
            EpistemicLabel.ACTED: "Externally executed operation (has real-world consequences)",
        }
        return descriptions[self]


class EpistemicViolation(Exception):
    """Raised when an epistemic invariant is violated."""
    pass


@dataclass
class EpistemicTransition:
    """
    Record of a transition between epistemic labels.

    Every transition is auditable. Downgrade (increasing label number)
    and upgrade (decreasing label number) have different requirements.
    """
    source_label: EpistemicLabel
    target_label: EpistemicLabel
    justification: str
    timestamp: float = field(default_factory=time.time)
    transition_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    evidence: Optional[Any] = None

    @property
    def is_upgrade(self) -> bool:
        """An upgrade moves toward more grounded (lower number)."""
        return self.target_label < self.source_label

    @property
    def is_downgrade(self) -> bool:
        """A downgrade moves toward less grounded (higher number)."""
        return self.target_label > self.source_label

    @property
    def is_forbidden(self) -> bool:
        """
        Some transitions are forbidden without explicit justification.

        Forbidden transitions:
            SIMULATED → OBSERVED (simulation is never observation)
            IMAGINED → REMEMBERED (imagination is never memory)
            PREDICTED → OBSERVED (prediction must be verified first)
        """
        forbidden = {
            (EpistemicLabel.SIMULATED, EpistemicLabel.OBSERVED),
            (EpistemicLabel.IMAGINED, EpistemicLabel.REMEMBERED),
            (EpistemicLabel.PREDICTED, EpistemicLabel.OBSERVED),
        }
        return (self.source_label, self.target_label) in forbidden


@dataclass
class EpistemicRepresentation:
    """
    An internal representation with full epistemic annotation.

    This is the fundamental data structure of the epistemic kernel.
    Every piece of information that flows through the system should
    be wrapped in an EpistemicRepresentation.
    """
    content: Any
    label: EpistemicLabel
    confidence: float = 1.0  # [0.0, 1.0]
    source: str = ""
    timestamp: float = field(default_factory=time.time)
    representation_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    provenance: list[EpistemicTransition] = field(default_factory=list)
    context: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        """Validate confidence bounds."""
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError(f"Confidence must be in [0.0, 1.0], got {self.confidence}")

    def transition_to(
        self,
        new_label: EpistemicLabel,
        justification: str,
        evidence: Optional[Any] = None,
    ) -> EpistemicRepresentation:
        """
        Transition this representation to a new epistemic label.

        Returns a NEW representation (immutability).
        Raises EpistemicViolation for forbidden transitions
        unless `justification` explicitly overrides.
        """
        transition = EpistemicTransition(
            source_label=self.label,
            target_label=new_label,
            justification=justification,
            evidence=evidence,
        )

        if transition.is_forbidden:
            # Forbidden transitions require a very strong justification
            # that explicitly acknowledges the epistemic violation
            # and provides evidence. We don't silently allow them.
            if not justification.startswith("EPISTEMIC_OVERRIDE:"):
                raise EpistemicViolation(
                    f"Epistemic invariant violation: cannot transition "
                    f"{self.label.name} → {new_label.name} without "
                    f"explicit override. Use 'EPISTEMIC_OVERRIDE: <reason>' "
                    f"as justification if you are certain."
                )

        # Create new representation with updated provenance
        new_provenance = self.provenance + [transition]
        return EpistemicRepresentation(
            content=self.content,
            label=new_label,
            confidence=self.confidence,
            source=self.source,
            timestamp=time.time(),
            representation_id=str(uuid.uuid4()),
            provenance=new_provenance,
            context=self.context.copy(),
        )

    def as_observed(self, justification: str, evidence: Any = None) -> EpistemicRepresentation:
        """Convenience: transition to OBSERVED."""
        return self.transition_to(EpistemicLabel.OBSERVED, justification, evidence)

    def as_inferred(self, justification: str) -> EpistemicRepresentation:
        """Convenience: transition to INFERRED."""
        return self.transition_to(EpistemicLabel.INFERRED, justification)

    def as_remembered(self, justification: str) -> EpistemicRepresentation:
        """Convenience: transition to REMEMBERED."""
        return self.transition_to(EpistemicLabel.REMEMBERED, justification)

    def as_predicted(self, justification: str) -> EpistemicRepresentation:
        """Convenience: transition to PREDICTED."""
        return self.transition_to(EpistemicLabel.PREDICTED, justification)

    def as_simulated(self, justification: str) -> EpistemicRepresentation:
        """Convenience: transition to SIMULATED."""
        return self.transition_to(EpistemicLabel.SIMULATED, justification)

    def as_imagined(self, justification: str) -> EpistemicRepresentation:
        """Convenience: transition to IMAGINED."""
        return self.transition_to(EpistemicLabel.IMAGINED, justification)

    def as_acted(self, justification: str) -> EpistemicRepresentation:
        """Convenience: transition to ACTED."""
        return self.transition_to(EpistemicLabel.ACTED, justification)

    @property
    def is_speculative(self) -> bool:
        """Whether this representation is speculative (not grounded)."""
        return self.label.is_speculative

    @property
    def is_groundable(self) -> bool:
        """Whether this representation could potentially be grounded."""
        return True  # All representations could potentially be grounded

    def audit_trail(self) -> list[dict]:
        """Return the full audit trail of epistemic transitions."""
        return [
            {
                "transition_id": t.transition_id,
                "source": t.source_label.name,
                "target": t.target_label.name,
                "justification": t.justification,
                "timestamp": t.timestamp,
                "is_upgrade": t.is_upgrade,
                "is_forbidden": t.is_forbidden,
            }
            for t in self.provenance
        ]


class EpistemicKernel:
    """
    The Epistemic Kernel manages epistemic labels and enforces invariants.

    It provides:
    - Factory methods for creating representations with proper labels
    - Validation of epistemic transitions
    - Audit logging of all transitions
    - Querying the epistemic status of any representation
    """

    def __init__(self):
        self._audit_log: list[EpistemicTransition] = []
        self._violation_count: int = 0

    def observe(self, content: Any, source: str = "", confidence: float = 1.0) -> EpistemicRepresentation:
        """Create an OBSERVED representation from sensor data or verified input."""
        return EpistemicRepresentation(
            content=content,
            label=EpistemicLabel.OBSERVED,
            confidence=confidence,
            source=source,
        )

    def infer(self, content: Any, from_representations: list[EpistemicRepresentation], justification: str = "") -> EpistemicRepresentation:
        """Create an INFERRED representation from other representations."""
        # Confidence is bounded by the minimum confidence of inputs
        min_conf = min((r.confidence for r in from_representations), default=1.0)
        return EpistemicRepresentation(
            content=content,
            label=EpistemicLabel.INFERRED,
            confidence=min_conf * 0.95,  # Small discount for inference
            source=f"inference from {len(from_representations)} representations",
            context={"input_ids": [r.representation_id for r in from_representations]},
        )

    def remember(self, content: Any, source: str = "", confidence: float = 0.9) -> EpistemicRepresentation:
        """Create a REMEMBERED representation from memory retrieval."""
        return EpistemicRepresentation(
            content=content,
            label=EpistemicLabel.REMEMBERED,
            confidence=confidence,
            source=source,
        )

    def predict(self, content: Any, source: str = "", confidence: float = 0.5) -> EpistemicRepresentation:
        """Create a PREDICTED representation for expected future states."""
        return EpistemicRepresentation(
            content=content,
            label=EpistemicLabel.PREDICTED,
            confidence=confidence,
            source=source,
        )

    def simulate(self, content: Any, source: str = "", confidence: float = 0.5) -> EpistemicRepresentation:
        """Create a SIMULATED representation from an internal model."""
        return EpistemicRepresentation(
            content=content,
            label=EpistemicLabel.SIMULATED,
            confidence=confidence,
            source=source,
        )

    def imagine(self, content: Any, source: str = "", confidence: float = 0.3) -> EpistemicRepresentation:
        """Create an IMAGINED representation (internally generated possibility)."""
        return EpistemicRepresentation(
            content=content,
            label=EpistemicLabel.IMAGINED,
            confidence=confidence,
            source=source,
        )

    def act(self, content: Any, source: str = "") -> EpistemicRepresentation:
        """Create an ACTED representation for externally executed operations."""
        return EpistemicRepresentation(
            content=content,
            label=EpistemicLabel.ACTED,
            confidence=1.0,  # Actions are certain (they happened)
            source=source,
        )

    def validate_transition(
        self,
        rep: EpistemicRepresentation,
        new_label: EpistemicLabel,
        justification: str,
    ) -> tuple[bool, Optional[str]]:
        """
        Validate a proposed epistemic transition.

        Returns (is_valid, error_message).
        """
        transition = EpistemicTransition(
            source_label=rep.label,
            target_label=new_label,
            justification=justification,
        )

        if transition.is_forbidden and not justification.startswith("EPISTEMIC_OVERRIDE:"):
            return False, (
                f"Forbidden transition: {rep.label.name} → {new_label.name}. "
                f"Use EPISTEMIC_OVERRIDE if certain."
            )

        return True, None

    def record_transition(self, transition: EpistemicTransition) -> None:
        """Record a transition in the audit log."""
        self._audit_log.append(transition)
        if transition.is_forbidden:
            self._violation_count += 1

    @property
    def violation_count(self) -> int:
        """Number of epistemic invariant violations (with override)."""
        return self._violation_count

    @property
    def audit_log(self) -> list[EpistemicTransition]:
        """Full audit log of all epistemic transitions."""
        return list(self._audit_log)

    def audit_summary(self) -> dict:
        """Summary statistics of the audit log."""
        if not self._audit_log:
            return {"total_transitions": 0, "upgrades": 0, "downgrades": 0, "violations": 0}

        return {
            "total_transitions": len(self._audit_log),
            "upgrades": sum(1 for t in self._audit_log if t.is_upgrade),
            "downgrades": sum(1 for t in self._audit_log if t.is_downgrade),
            "violations": self._violation_count,
            "forbidden_with_override": sum(1 for t in self._audit_log if t.is_forbidden),
        }
