"""
Imagination Engine — Counterfactual Simulation and Decision Interface.

Creates an explicit distinction between:
    Hypothesis → Simulation → Decision → Execution

Architecture:
    Current World State → Imagination Engine
        ├── Counterfactual A
        ├── Counterfactual B
        └── Counterfactual C
        → Outcome Evaluation → Candidate Action
        → Policy / Safety Check → Execution

CRITICAL: High-risk actions must NEVER be automatically executed merely
because an imagined scenario predicts a positive outcome.

Implementation Status: IMPLEMENTED
"""

from __future__ import annotations

import time
import uuid
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Optional, Callable

from nuros.epistemic import EpistemicLabel, EpistemicKernel, EpistemicRepresentation


class ImaginationStage(Enum):
    HYPOTHESIS = "hypothesis"
    SIMULATION = "simulation"
    EVALUATION = "evaluation"
    DECISION = "decision"
    EXECUTION = "execution"


class RiskLevel(Enum):
    NONE = 0
    LOW = 1
    MEDIUM = 2
    HIGH = 3
    CRITICAL = 4


@dataclass
class Counterfactual:
    """A counterfactual scenario generated by the imagination engine."""
    scenario_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    description: str = ""
    world_state: dict[str, Any] = field(default_factory=dict)
    predicted_outcome: Optional[dict] = None
    utility_score: float = 0.0
    risk_level: RiskLevel = RiskLevel.NONE
    epistemic_rep: Optional[EpistemicRepresentation] = None
    timestamp: float = field(default_factory=time.time)
    parent_scenario: Optional[str] = None


@dataclass
class ImaginationResult:
    """Result of an imagination cycle."""
    result_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    counterfactuals: list[Counterfactual] = field(default_factory=list)
    selected_scenario: Optional[Counterfactual] = None
    decision: Optional[str] = None
    executed: bool = False
    rejection_reason: str = ""
    timestamp: float = field(default_factory=time.time)


class ImaginationEngine:
    """
    The Imagination Engine — Counterfactual simulation and decision.

    Generates counterfactual scenarios, evaluates outcomes, and selects
    candidate actions. High-risk actions require explicit approval.

    The epistemic kernel ensures that imagined and simulated states
    are NEVER confused with observed or factual states.
    """

    def __init__(self, epistemic_kernel: Optional[EpistemicKernel] = None):
        self._epistemic = epistemic_kernel or EpistemicKernel()
        self._scenario_history: list[ImaginationResult] = []
        self._risk_threshold: RiskLevel = RiskLevel.HIGH
        self._require_approval_above: RiskLevel = RiskLevel.MEDIUM
        self._max_counterfactuals: int = 5

    def hypothesize(
        self,
        current_state: dict[str, Any],
        possible_actions: list[str],
        world_model: Optional[Callable] = None,
    ) -> list[Counterfactual]:
        """
        Generate counterfactual hypotheses from possible actions.
        
        Each hypothesis is an IMAGINED epistemic state.
        """
        counterfactuals = []
        for i, action in enumerate(possible_actions[:self._max_counterfactuals]):
            cf = Counterfactual(
                description=f"If I do: {action}",
                world_state=dict(current_state),
            )
            # Create epistemic representation — always IMAGINED
            cf.epistemic_rep = self._epistemic.imagine(
                content={"action": action, "from_state": current_state},
                source="imagination_engine",
            )

            if world_model:
                try:
                    predicted = world_model(current_state, action)
                    cf.predicted_outcome = predicted
                    # Transition to SIMULATED once we run the model
                    cf.epistemic_rep = cf.epistemic_rep.as_simulated(
                        "Ran world model simulation"
                    )
                except Exception as e:
                    cf.predicted_outcome = {"error": str(e)}

            counterfactuals.append(cf)

        return counterfactuals

    def evaluate(
        self,
        counterfactuals: list[Counterfactual],
        utility_function: Optional[Callable] = None,
        risk_function: Optional[Callable] = None,
    ) -> list[Counterfactual]:
        """
        Evaluate counterfactual scenarios using utility and risk functions.
        """
        for cf in counterfactuals:
            if utility_function and cf.predicted_outcome:
                try:
                    cf.utility_score = utility_function(cf.predicted_outcome)
                except Exception:
                    cf.utility_score = 0.0

            if risk_function and cf.predicted_outcome:
                try:
                    risk_val = risk_function(cf.predicted_outcome)
                    cf.risk_level = self._categorize_risk(risk_val)
                except Exception:
                    cf.risk_level = RiskLevel.MEDIUM

        # Sort by utility score (descending)
        counterfactuals.sort(key=lambda c: c.utility_score, reverse=True)
        return counterfactuals

    def decide(
        self,
        counterfactuals: list[Counterfactual],
        allow_high_risk: bool = False,
    ) -> ImaginationResult:
        """
        Select the best action from evaluated counterfactuals.
        
        High-risk actions are rejected unless explicitly approved.
        CRITICAL: This never automatically executes — it only proposes.
        """
        result = ImaginationResult(counterfactuals=counterfactuals)

        if not counterfactuals:
            result.decision = "no_action"
            result.rejection_reason = "No counterfactuals available"
            self._scenario_history.append(result)
            return result

        # Filter out high-risk scenarios unless explicitly allowed
        candidates = [
            cf for cf in counterfactuals
            if allow_high_risk or cf.risk_level.value < self._require_approval_above.value
        ]

        if not candidates:
            result.decision = "rejected_all_high_risk"
            result.rejection_reason = (
                f"All scenarios exceed risk threshold ({self._require_approval_above.name}). "
                f"Human approval required."
            )
            result.selected_scenario = counterfactuals[0]
            self._scenario_history.append(result)
            return result

        # Select the highest-utility candidate
        selected = candidates[0]
        result.selected_scenario = selected
        result.decision = selected.description

        self._scenario_history.append(result)
        return result

    def execute_check(self, result: ImaginationResult) -> tuple[bool, str]:
        """
        Final safety check before execution.
        
        Returns (allowed, reason).
        This is a GATE, not automatic execution.
        """
        if not result.selected_scenario:
            return False, "No scenario selected"

        if result.selected_scenario.risk_level.value >= RiskLevel.HIGH.value:
            return False, (
                f"Risk level {result.selected_scenario.risk_level.name} "
                f"requires human approval. Do NOT auto-execute."
            )

        if result.selected_scenario.epistemic_rep and result.selected_scenario.epistemic_rep.is_speculative:
            # The scenario is still speculative — it has not been verified
            # against reality. This is OK for planning but NOT for auto-execution.
            pass  # Allow planning to proceed

        return True, "Cleared for execution pending human approval"

    def _categorize_risk(self, risk_value: float) -> RiskLevel:
        """Categorize a numeric risk value into a RiskLevel."""
        if risk_value <= 0.1:
            return RiskLevel.NONE
        elif risk_value <= 0.3:
            return RiskLevel.LOW
        elif risk_value <= 0.6:
            return RiskLevel.MEDIUM
        elif risk_value <= 0.8:
            return RiskLevel.HIGH
        else:
            return RiskLevel.CRITICAL

    @property
    def history(self) -> list[ImaginationResult]:
        return list(self._scenario_history)

    def summary(self) -> dict:
        return {
            "total_scenarios_evaluated": len(self._scenario_history),
            "risk_threshold": self._risk_threshold.name,
            "max_counterfactuals": self._max_counterfactuals,
        }
